dist: bionic

language: node_js
node_js:
  - lts/*

addons:
  chrome: beta
  firefox: latest
  apt:
    packages:
      - xvfb
      - ubuntu-restricted-addons

before_install:
  - sudo update-alternatives --set google-chrome /usr/bin/google-chrome-beta

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm run lint || travis_terminate 1
  - npm run build || travis_terminate 1
  - npm run test || travis_terminate 1
  - npm run docs || travis_terminate 1

cache:
  directories:
    - node_modules
